# Generated by Django 4.2.1 on 2023-05-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('image_link', models.CharField(max_length=30)),
                ('facebook_link', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=30)),
                ('seeking_venue', models.BooleanField()),
                ('seeking_description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('image_link', models.CharField(max_length=30)),
                ('facebook_link', models.CharField(max_length=30)),
                ('website', models.CharField(max_length=30)),
                ('seeking_talent', models.BooleanField()),
                ('seeking_description', models.CharField(max_length=30)),
            ],
        ),
    ]
