# Generated by Django 4.2.1 on 2023-05-11 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyyur.artist')),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fyyur.venue')),
            ],
        ),
    ]
