# Generated by Django 4.2.1 on 2023-05-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0002_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='artist_id',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='venue_id',
            new_name='venue',
        ),
    ]
