# Generated by Django 4.2.1 on 2023-05-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyyur', '0004_alter_venue_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
